import { Outfit } from "next/font/google";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Login - Award Champions",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}

