export const brandData = [
    {
        brandName: "Coralcal",
        brandCode: "CORALCAL",
        tableData: [
            { territoryId: "T001", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "T002", rankAchievement: 2, rankOverAvgGrowth: 3, cumulativeRank: 5 },
            { territoryId: "T003", rankAchievement: 3, rankOverAvgGrowth: 4, cumulativeRank: 7 },
            { territoryId: "T004", rankAchievement: 4, rankOverAvgGrowth: 5, cumulativeRank: 9 },
            { territoryId: "T011", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "T012", rankAchievement: 2, rankOverAvgGrowth: 3, cumulativeRank: 5 },
            { territoryId: "T013", rankAchievement: 3, rankOverAvgGrowth: 4, cumulativeRank: 7 },
            { territoryId: "T014", rankAchievement: 4, rankOverAvgGrowth: 5, cumulativeRank: 9 },
            { territoryId: "T021", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "T022", rankAchievement: 2, rankOverAvgGrowth: 3, cumulativeRank: 5 },
            { territoryId: "T023", rankAchievement: 3, rankOverAvgGrowth: 4, cumulativeRank: 7 },
            { territoryId: "T024", rankAchievement: 4, rankOverAvgGrowth: 5, cumulativeRank: 9 },
        ],
    },
    {
        brandName: "Exium",
        brandCode: "EXIUM",
        tableData: [
            { territoryId: "T004", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "T003", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "T001", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T002", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "T0014", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "T0013", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "T0011", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T0022", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "T0034", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "T0043", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "T0021", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T0022", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
        ],
    },
    {
        brandName: "Rivotril",
        brandCode: "RIVOTRIL",
        tableData: [
            { territoryId: "T005", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "T006", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "T001", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T003", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "T0015", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "T0016", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "T0021", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T0033", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "T0055", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "T0046", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "T0031", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T0023", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
        ],
    },
    {
        brandName: "Gavirad",
        brandCode: "GAVIRAD",
        tableData: [
            { territoryId: "T007", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "T008", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "T009", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T0037", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "T0028", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "T0049", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T0087", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "T0038", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "T0049", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "T0027", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "T0048", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "T0019", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
        ],
    },
];
