export const brandData = [
    {
        brandName: "Coralcal",
        brandCode: "CORALCAL",
        tableData: [
            { territoryId: "10001", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "10002", rankAchievement: 2, rankOverAvgGrowth: 3, cumulativeRank: 5 },
            { territoryId: "10003", rankAchievement: 3, rankOverAvgGrowth: 4, cumulativeRank: 7 },
            { territoryId: "10004", rankAchievement: 4, rankOverAvgGrowth: 5, cumulativeRank: 9 },
            { territoryId: "10005", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "10006", rankAchievement: 2, rankOverAvgGrowth: 3, cumulativeRank: 5 },
            { territoryId: "10007", rankAchievement: 3, rankOverAvgGrowth: 4, cumulativeRank: 7 },
            { territoryId: "10008", rankAchievement: 4, rankOverAvgGrowth: 5, cumulativeRank: 9 },
            { territoryId: "10009", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "10010", rankAchievement: 2, rankOverAvgGrowth: 3, cumulativeRank: 5 },
            { territoryId: "18005", rankAchievement: 4, rankOverAvgGrowth: 3, cumulativeRank: 7 },
            { territoryId: "10011", rankAchievement: 3, rankOverAvgGrowth: 4, cumulativeRank: 7 },
            { territoryId: "10012", rankAchievement: 4, rankOverAvgGrowth: 5, cumulativeRank: 9 },
        ],
    },
    {
        brandName: "Exium",
        brandCode: "EXIUM",
        tableData: [
            { territoryId: "10013", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "10014", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "10015", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10016", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "10017", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "10018", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "10019", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10020", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "10021", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "10022", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "10023", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10024", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
        ],
    },
    {
        brandName: "Rivotril",
        brandCode: "RIVOTRIL",
        tableData: [
            { territoryId: "10025", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "10026", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "10027", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10028", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "10029", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "10030", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "10031", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10034", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
            { territoryId: "10035", rankAchievement: 1, rankOverAvgGrowth: 1, cumulativeRank: 2 },
            { territoryId: "10036", rankAchievement: 2, rankOverAvgGrowth: 2, cumulativeRank: 4 },
            { territoryId: "10037", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10038", rankAchievement: 4, rankOverAvgGrowth: 4, cumulativeRank: 8 },
        ],
    },
    {
        brandName: "Gavirad",
        brandCode: "GAVIRAD",
        tableData: [
            { territoryId: "10039", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "10040", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "10041", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10042", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "10043", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "10044", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10045", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "10046", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "10047", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
            { territoryId: "10048", rankAchievement: 1, rankOverAvgGrowth: 2, cumulativeRank: 3 },
            { territoryId: "10049", rankAchievement: 2, rankOverAvgGrowth: 1, cumulativeRank: 3 },
            { territoryId: "10050", rankAchievement: 3, rankOverAvgGrowth: 3, cumulativeRank: 6 },
        ],
    },
];
