export const championshipData = {
  teams: [
    {
      teamCode: "A",
      teamName: "Team A",
      totalZones: 4,
      zones: [
        {
          zoneCode: "A-Z1",
          zoneName: "Dhaka-I (GEN-A)",
          achievementPercent: 92,
          growthPercent: 18,
          cumulativeRank: 110, 
        },
        {
          zoneCode: "A-Z2",
          zoneName: "Savar (GEN-A)",
          achievementPercent: 88,
          growthPercent: 22,
          cumulativeRank: 110,
        },
        {
          zoneCode: "A-Z3",
          zoneName: "Tangail (GEN-A)",
          achievementPercent: 95,
          growthPercent: 15,
          cumulativeRank: 110,
        },
        {
          zoneCode: "A-Z4",
          zoneName: "Bogura (GEN-A)",
          achievementPercent: 40,
          growthPercent: 20,
          cumulativeRank: 60,
        },
        {
          zoneCode: "A-Z5",
          zoneName: "Dinajpur (GEN-A)",
          achievementPercent: 90,
          growthPercent: 20,
          cumulativeRank: 110,
        },
        {
          zoneCode: "A-Z6",
          zoneName: "Rangpur (GEN-A)",
          achievementPercent: 80,
          growthPercent: 20,
          cumulativeRank: 100,
        },
        {
          zoneCode: "A-Z7",
          zoneName: "Kushtia (GEN-A)",
          achievementPercent: 70,
          growthPercent: 20,
          cumulativeRank: 90,
        },
        {
          zoneCode: "A-Z8",
          zoneName: "Jashore (GEN-A)",
          achievementPercent: 80,
          growthPercent: 20,
          cumulativeRank: 100,
        },
        {
          zoneCode: "A-Z9",
          zoneName: "Barishal-A (GEN-A)",
          achievementPercent: 40,
          growthPercent: 20,
          cumulativeRank: 60,
        },
        {
          zoneCode: "A-30",
          zoneName: "Khulna (GEN-A)",
          achievementPercent: 20,
          growthPercent: 20,
          cumulativeRank: 40,
        },
        {
          zoneCode: "A-31",
          zoneName: "Faridpur (GEN-A)",
          achievementPercent: 60,
          growthPercent: 30,
          cumulativeRank: 90,
        },
        {
          zoneCode: "A-32",
          zoneName: "Dhaka-D (GEN-A)",
          achievementPercent: 80,
          growthPercent: 20,
          cumulativeRank: 100,
        },
        {
          zoneCode: "A-33",
          zoneName: "Narayangonj (GEN-A)",
          achievementPercent: 80,
          growthPercent: 40,
          cumulativeRank: 120,
        },
        {
          zoneCode: "A-34",
          zoneName: "Narsingdi (GEN-A)",
          achievementPercent: 50,
          growthPercent: 40,
          cumulativeRank: 90,
        },
        {
          zoneCode: "A-35",
          zoneName: "Dhaka-B (GEN-A)",
          achievementPercent: 65,
          growthPercent: 40,
          cumulativeRank: 105,
        },
        {
          zoneCode: "A-36",
          zoneName: "Sylhet-A (GEN-A)",
          achievementPercent: 55,
          growthPercent: 40,
          cumulativeRank: 95,
        },
        {
          zoneCode: "A-37",
          zoneName: "Sylhet-B (GEN-A)",
          achievementPercent: 45,
          growthPercent: 20,
          cumulativeRank: 65,
        },
        {
          zoneCode: "A-38",
          zoneName: "B. Baria (GEN-A)",
          achievementPercent: 30,
          growthPercent: 40,
          cumulativeRank: 70,
        },
        {
          zoneCode: "A-39",
          zoneName: "Uttara (GEN-A)",
          achievementPercent: 35,
          growthPercent: 35,
          cumulativeRank: 70,
        },
        {
          zoneCode: "A-39",
          zoneName: "Gazipur (GEN-A)",
          achievementPercent: 72,
          growthPercent: 23,
          cumulativeRank: 95,
        },
        {
          zoneCode: "A-40",
          zoneName: "Dhaka-A (GEN-A)",
          achievementPercent: 49,
          growthPercent: 31,
          cumulativeRank: 80,
        },
        {
          zoneCode: "A-41",
          zoneName: "Mymensingh (GEN-A)",
          achievementPercent: 56,
          growthPercent: 44,
          cumulativeRank: 100,
        },
      ],
    },
    {
      teamCode: "B",
      teamName: "Team B",
      totalZones: 2,
      zones: [
        {
          zoneCode: "B-Z1",
          zoneName: "Bhola (GEN-B)",
          achievementPercent: 87,
          growthPercent: 19,
          cumulativeRank: 106,
        },
        {
          zoneCode: "B-Z2",
          zoneName: "Monpura (GEN-B)",
          achievementPercent: 91,
          growthPercent: 16,
          cumulativeRank: 107,
        },
      ],
    },
    {
      teamCode: "C",
      teamName: "Team C",
      totalZones: 1,
      zones: [
        {
          zoneCode: "C-Z1",
          zoneName: "Mirpur (GEN-C)",
          achievementPercent: 94,
          growthPercent: 21,
          cumulativeRank: 115,
        },
      ],
    },
    {
      teamCode: "N",
      teamName: "Team RNL",
      totalZones: 2,
      zones: [
        {
          zoneCode: "RNL-Z1",
          zoneName: "Gajipur (GEN-N)",
          achievementPercent: 89,
          growthPercent: 17,
          cumulativeRank: 106,
        },
        {
          zoneCode: "RNL-Z2",
          zoneName: "Savar (GEN-N)",
          achievementPercent: 93,
          growthPercent: 14,
          cumulativeRank: 107,
        },
      ],
    },
  ],
};
